apiVersion: apps/v1
kind: Deployment
metadata:
  name: upd-dep
  labels:
    app: upd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: upd
  template:
    metadata:
      labels:
        app: upd
    spec:
      containers:
      - name: upd
        image: 192.168.7.41:5000/kpavel/lithops_runtime:13.0
        imagePullPolicy: Always
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
